-- CONNECT SYSTEM
ALTER SESSION SET EVENTS '10150 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10904 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '25475 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10407 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10851 TRACE NAME CONTEXT FOREVER, LEVEL 1';
GSMADMIN_INTERNAL.DBMS_GSM_UTILITY.TurnOffTrigger routine
ALTER SESSION SET EVENTS '22830 TRACE NAME CONTEXT FOREVER, LEVEL 192 ';
-- new object type path: SCHEMA_EXPORT/USER
 CREATE USER "SYSPR1" IDENTIFIED BY VALUES 'S:4013D90435F6FBB10F058FF8AABD136936B066A559F42732C265CDA7C14A;T:CB249A13F6A500BD610C8ADCB13D2751AF253AE2FBD4FA32084AAE1BA2A9B5311604F63D8B1A337A53E985DECF1A6DE958A1D7FB7636CDCD6E01923E2B980E4D4D608554D835EC0E92F449F03BBDAACA'
      DEFAULT TABLESPACE "USERS"
      TEMPORARY TABLESPACE "TEMP" CONTAINER=ALL;
-- new object type path: SCHEMA_EXPORT/SYSTEM_GRANT
GRANT CREATE PROCEDURE TO "SYSPR1";
GRANT CREATE VIEW TO "SYSPR1";
GRANT CREATE TABLE TO "SYSPR1";
GRANT CREATE SESSION TO "SYSPR1";
-- new object type path: SCHEMA_EXPORT/ROLE_GRANT
 GRANT "CONNECT" TO "SYSPR1";
-- new object type path: SCHEMA_EXPORT/DEFAULT_ROLE
 ALTER USER "SYSPR1" DEFAULT ROLE ALL;
-- new object type path: SCHEMA_EXPORT/PRE_SCHEMA/PROCACT_SCHEMA
-- new object type path: SCHEMA_EXPORT/PRE_SCHEMA/PROCACT_SCHEMA/LOGREP
-- CONNECT SYSPR1

BEGIN 
sys.dbms_logrep_imp.instantiate_schema(schema_name=>SYS_CONTEXT('USERENV','CURRENT_SCHEMA'), export_db_name=>'FREE', inst_scn=>'3278507');
COMMIT; 
END; 
/ 
-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
-- CONNECT SYSTEM
CREATE TABLE "SYSPR1"."BARRIOS" 
   (	"BARR_ID_BARRIO" NUMBER(4,0) NOT NULL ENABLE, 
	"BARR_DESCRIPCION" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"BARR_ID_SECUENCIADOR" NUMBER(4,0) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE TABLE "SYSPR1"."CIUDADES" 
   (	"CIUD_ID_CIUDAD" NUMBER(4,0) NOT NULL ENABLE, 
	"CIUD_DESCRIPCION" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CIUD_ID_SECUENCIADOR" NUMBER(4,0) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE TABLE "SYSPR1"."PERSONAS_SOCIOS" 
   (	"PESO_NRO_SOCIO" NUMBER(9,0) NOT NULL ENABLE, 
	"PESO_COD_PERSONA" NUMBER(9,0) NOT NULL ENABLE, 
	"PESO_INGRESO" DATE NOT NULL ENABLE, 
	"PESO_SITUACION_SOCIO" NUMBER(1,0) NOT NULL ENABLE, 
	"PESO_ACTIVO" NUMBER(1,0) NOT NULL ENABLE, 
	"PESO_ID_SECUENCIADOR_TABLA" NUMBER(4,0) NOT NULL ENABLE, 
	"PESO_NRO_MESA" NUMBER(9,0), 
	"PESO_NRO_SOL_INGRESO" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 3145728
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE TABLE "SYSPR1"."PERSONAS" 
   (	"PERS_COD_PERSONA" NUMBER(9,0), 
	"PERS_SERIE_CI" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"PERS_CI" NUMBER(8,0) NOT NULL ENABLE, 
	"PERS_NOMBRE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PERS_APELLIDO" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"PERS_FECHA_NACIMIENTO" DATE, 
	"PERS_ESTADO_CIVIL" NUMBER(1,0) NOT NULL ENABLE, 
	"PERS_SEXO" NUMBER(1,0) NOT NULL ENABLE, 
	"PERS_ID_CIUDAD" NUMBER(4,0) NOT NULL ENABLE, 
	"PERS_ID_PAIS" NUMBER(4,0) NOT NULL ENABLE, 
	"PERS_ID_SECUENCIADOR" NUMBER(4,0) NOT NULL ENABLE, 
	"PERS_NRO_FUNCIONARIO" NUMBER(7,0), 
	"PERS_FECHA_USUARIO" DATE, 
	"PERS_ID_SUCURSAL" NUMBER(4,0), 
	"PERS_RUC" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 8388608
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE TABLE "SYSPR1"."FUNCIONARIOS" 
   (	"FUNC_NRO_FUNCIONARIO" NUMBER(7,0) NOT NULL ENABLE, 
	"FUNC_FECHA_INGRESO" DATE, 
	"FUNC_IPS" VARCHAR2(12 BYTE), 
	"FUNC_HIJOS_MENORES" NUMBER(2,0) DEFAULT 0, 
	"FUNC_HIJOS_MAYORES" NUMBER(2,0), 
	"FUNC_COD_PERSONA" NUMBER(9,0) NOT NULL ENABLE, 
	"FUNC_ID_NIVEL_SALARIO" NUMBER(4,0), 
	"FUNC_ID_ORGANIGRAMA" NUMBER(4,0), 
	"FUNC_ID_ORGANIGRAMA_RESOL_FUNC" NUMBER(4,0), 
	"FUNC_NRO_ACTA" NUMBER(8,0), 
	"FUNC_NRO_RESOL_FUNC" NUMBER(7,0), 
	"FUNC_PERIODO" DATE, 
	"FUNC_ID_CARGO" NUMBER(4,0), 
	"FUNC_TIPO_HORARIO" VARCHAR2(1 BYTE), 
	"FUNC_USUARIO" VARCHAR2(20 BYTE), 
	"FUNC_ACTIVO" NUMBER(1,0) NOT NULL ENABLE, 
	"FUNC_PERIODO_MES" NUMBER(3,0), 
	"FUNC_ID_SECUENCIADOR" NUMBER(4,0), 
	"FUNC_TIPO_FUNCIONARIO" NUMBER(1,0), 
	"FUNC_BONIFICA" VARCHAR2(1 BYTE), 
	"FUNC_FECHA_EGRESO" DATE, 
	"FUNC_ANTICIPO" NUMBER(6,3), 
	"FUNC_COMEDOR" NUMBER(4,0), 
	"FUNC_PLA_IPS" NUMBER(1,0), 
	"FUNC_PLA_SUELDO" NUMBER(1,0), 
	"FUNC_INCENTIVO" NUMBER(20,2), 
	"FUNC_MONTO_ANTICIPO" NUMBER(20,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE TABLE "SYSPR1"."PAISES" 
   (	"PAIS_ID_PAIS" NUMBER(4,0) NOT NULL ENABLE, 
	"PAIS_DESCRIPCION" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"PAIS_ID_SECUENCIADOR" NUMBER(4,0) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE TABLE "SYSPR1"."CALLES" 
   (	"CALL_ID_CALLES" NUMBER(5,0) NOT NULL ENABLE, 
	"CALL_DESCRIPCION" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"CALL_ID_SECUENCIADOR" NUMBER(4,0) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 3145728
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
-- new object type path: SCHEMA_EXPORT/TABLE/COMMENT
 COMMENT ON COLUMN "SYSPR1"."BARRIOS"."BARR_ID_BARRIO" IS 'Codigo identificador del Barrio';
 COMMENT ON COLUMN "SYSPR1"."BARRIOS"."BARR_DESCRIPCION" IS 'Descripcion del Barrio';
 COMMENT ON COLUMN "SYSPR1"."BARRIOS"."BARR_ID_SECUENCIADOR" IS 'Codigo identificador de la Tabla';
 COMMENT ON COLUMN "SYSPR1"."CIUDADES"."CIUD_ID_CIUDAD" IS 'Codigo identificador de la Ciudad';
 COMMENT ON COLUMN "SYSPR1"."CIUDADES"."CIUD_DESCRIPCION" IS 'Nombre de la Ciudad';
 COMMENT ON COLUMN "SYSPR1"."CIUDADES"."CIUD_ID_SECUENCIADOR" IS 'Codigo identificador de la Tabla';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS_SOCIOS"."PESO_NRO_SOCIO" IS 'Numero del Socio';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS_SOCIOS"."PESO_COD_PERSONA" IS 'Codigo identificador de la persona';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS_SOCIOS"."PESO_INGRESO" IS 'Ingrerso como socio de la cooperativa';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS_SOCIOS"."PESO_SITUACION_SOCIO" IS 'Situacion del Socio';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS_SOCIOS"."PESO_ACTIVO" IS 'Indica si esta activo o inactivo';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS_SOCIOS"."PESO_ID_SECUENCIADOR_TABLA" IS 'Codigo identificador de la Tabla';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS_SOCIOS"."PESO_NRO_MESA" IS 'Numero de Mesa';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS_SOCIOS"."PESO_NRO_SOL_INGRESO" IS 'Numero de solicitud correspondiente';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_COD_PERSONA" IS 'Codigo identificador de la persona';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_SERIE_CI" IS 'Serie de la Cedula de Identidad';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_CI" IS 'Numero de Cedula de Identidad';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_NOMBRE" IS 'Nombre del Socio';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_APELLIDO" IS 'Apellido del Socio';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_FECHA_NACIMIENTO" IS 'Fecha de Nacimiento del Socio';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_ID_CIUDAD" IS 'Codigo identificador de la Ciudad';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_ID_PAIS" IS 'Codigo identificador del pais';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_ID_SECUENCIADOR" IS 'Codigo Secuenciador Tabla';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_NRO_FUNCIONARIO" IS 'Nro. de Funcionario';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_FECHA_USUARIO" IS 'Fecha de ultimo movimiento del usuario';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_ID_SUCURSAL" IS 'Sucursal a la cual pertenece la persona';
 COMMENT ON COLUMN "SYSPR1"."PERSONAS"."PERS_RUC" IS 'RUC de la persona o de la entidad';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_NRO_FUNCIONARIO" IS 'Nro identificador del funcionario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_FECHA_INGRESO" IS 'Fecha de ingreso del funcionario a la cooperativa';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_IPS" IS 'Numero de IPS del funcionario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_HIJOS_MENORES" IS 'Cantidad de hijos del funcionario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_HIJOS_MAYORES" IS 'Cantidad de hijos mayores';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_COD_PERSONA" IS 'Codigo identificador de la persona';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_ID_NIVEL_SALARIO" IS 'Identificador del nivel de salario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_ID_ORGANIGRAMA" IS 'Codigo identificador del comite';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_ID_ORGANIGRAMA_RESOL_FUNC" IS 'Codigo identificador del comite';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_NRO_ACTA" IS 'Nro. identificador por resolucion.';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_NRO_RESOL_FUNC" IS 'Numero identificador de resolucion que habilita como funcionario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_PERIODO" IS 'Periodo de la politica salarial';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_ID_CARGO" IS 'Codigo identificador de cargos.';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_TIPO_HORARIO" IS 'tipo de horario normal';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_USUARIO" IS 'Password del Usuario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_ACTIVO" IS 'Indica si esta activo o inactivo';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_PERIODO_MES" IS 'Periodo en cantidad de meses de la politica salarial del funcionario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_ID_SECUENCIADOR" IS 'Nro del secuenciador de funcionario en la tabla Secuenciadores Tablas';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_TIPO_FUNCIONARIO" IS 'Tipo de funcionario, distinguira especificamente a cada trabajador de la cooperativa';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_BONIFICA" IS 'Bonificacion (S=Si / N=No).';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_FECHA_EGRESO" IS 'Fecha en que egreso el funcionario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_ANTICIPO" IS 'Porcentaje de anticipo de salario del funcionario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_COMEDOR" IS 'Identificador del comedor al que pertenecera el funcionario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_PLA_IPS" IS 'Indicara si el funcionario figurara en la planilla para IPS';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_PLA_SUELDO" IS 'Indicara si el funcionario figurara en la planilla de sueldo';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_INCENTIVO" IS 'Monto correspondiente al incentivo por funcionario';
 COMMENT ON COLUMN "SYSPR1"."FUNCIONARIOS"."FUNC_MONTO_ANTICIPO" IS 'Monto correspondiente al anticipo de sueldo que le corresponde al funcionario';
 COMMENT ON COLUMN "SYSPR1"."PAISES"."PAIS_ID_PAIS" IS 'Codigo identificador del pais';
 COMMENT ON COLUMN "SYSPR1"."PAISES"."PAIS_DESCRIPCION" IS 'Nombre del pais';
 COMMENT ON COLUMN "SYSPR1"."PAISES"."PAIS_ID_SECUENCIADOR" IS 'Codigo identificador de la Tabla';
 COMMENT ON COLUMN "SYSPR1"."CALLES"."CALL_ID_CALLES" IS 'Codigo Identificador de la Calle';
 COMMENT ON COLUMN "SYSPR1"."CALLES"."CALL_DESCRIPCION" IS 'Nombre de la Calle';
 COMMENT ON COLUMN "SYSPR1"."CALLES"."CALL_ID_SECUENCIADOR" IS 'Codigo identificador de la Tabla';
-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
-- CONNECT SYSPR1
CREATE UNIQUE INDEX "SYSPR1"."BARR_BARRIO_PK" ON "SYSPR1"."BARRIOS" ("BARR_ID_BARRIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."BARR_SECUENCIA_TABLA_FK_I" ON "SYSPR1"."BARRIOS" ("BARR_ID_SECUENCIADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SYSPR1"."BARR_DESCRIPCION_UK" ON "SYSPR1"."BARRIOS" ("BARR_DESCRIPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."CIUD_SECUENCIA_TABLA_FK_I" ON "SYSPR1"."CIUDADES" ("CIUD_ID_SECUENCIADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SYSPR1"."CIUD_CIUDAD_PK" ON "SYSPR1"."CIUDADES" ("CIUD_ID_CIUDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SYSPR1"."PESO_PERSONA_SOCIO_PK" ON "SYSPR1"."PERSONAS_SOCIOS" ("PESO_COD_PERSONA", "PESO_NRO_SOCIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 2097152
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."PESO_SOL_INGRESO_FK_I" ON "SYSPR1"."PERSONAS_SOCIOS" ("PESO_NRO_SOL_INGRESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 2097152
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SYSPR1"."PESO_NRO_SOCIO_UK" ON "SYSPR1"."PERSONAS_SOCIOS" ("PESO_NRO_SOCIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 2097152
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."PESO_PERSONA_FK_I" ON "SYSPR1"."PERSONAS_SOCIOS" ("PESO_COD_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 2097152
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."PESO_MESA_FK_I" ON "SYSPR1"."PERSONAS_SOCIOS" ("PESO_NRO_MESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."PESO_SECUENCIADOR_TABLA_FK_I" ON "SYSPR1"."PERSONAS_SOCIOS" ("PESO_ID_SECUENCIADOR_TABLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 2097152
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."PERS_FUNCIONARIO_FK_I" ON "SYSPR1"."PERSONAS" ("PERS_NRO_FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 3145728
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."PERS_PAIS_FK_I" ON "SYSPR1"."PERSONAS" ("PERS_ID_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 2097152
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."PERS_CIUDAD_FK_I" ON "SYSPR1"."PERSONAS" ("PERS_ID_CIUDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 4194304
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SYSPR1"."PERS_PERSONA_PK" ON "SYSPR1"."PERSONAS" ("PERS_COD_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 2097152
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."INDX_PERS_ID_SECUENCIADOR" ON "SYSPR1"."PERSONAS" ("PERS_ID_SECUENCIADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 2097152
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SYSPR1"."FUNC_FUNCIONARIO_PK" ON "SYSPR1"."FUNCIONARIOS" ("FUNC_NRO_FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."FUNC_ORGANIGRAMA_FK_I" ON "SYSPR1"."FUNCIONARIOS" ("FUNC_ID_ORGANIGRAMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."FUNC_RESOL_FUNC_FK_I" ON "SYSPR1"."FUNCIONARIOS" ("FUNC_ID_ORGANIGRAMA_RESOL_FUNC", "FUNC_NRO_ACTA", "FUNC_NRO_RESOL_FUNC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."FUNC_SECUENCIADOR_TABLA_FK_I" ON "SYSPR1"."FUNCIONARIOS" ("FUNC_ID_SECUENCIADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SYSPR1"."FUNC_USUARIO_INX" ON "SYSPR1"."FUNCIONARIOS" ("FUNC_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."FUNC_PERSONA_FK_I" ON "SYSPR1"."FUNCIONARIOS" ("FUNC_COD_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."FUNC_HORARIO_NORMAL_FK_I" ON "SYSPR1"."FUNCIONARIOS" ("FUNC_TIPO_HORARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."PAIS_SECUENCIA_TABLA_FK_I" ON "SYSPR1"."PAISES" ("PAIS_ID_SECUENCIADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SYSPR1"."PAIS_PK" ON "SYSPR1"."PAISES" ("PAIS_ID_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SYSPR1"."PAIS_DESCRIPCION_UK" ON "SYSPR1"."PAISES" ("PAIS_DESCRIPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SYSPR1"."CALL_CALLE_PK" ON "SYSPR1"."CALLES" ("CALL_ID_CALLES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 2097152
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
CREATE INDEX "SYSPR1"."CALL_SECUENCIA_TABLA_FK_I" ON "SYSPR1"."CALLES" ("CALL_ID_SECUENCIADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 720896
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT
-- CONNECT SYSTEM
ALTER TABLE "SYSPR1"."BARRIOS" ADD CONSTRAINT "BARR_BARRIO_PK" PRIMARY KEY ("BARR_ID_BARRIO")
  USING INDEX "SYSPR1"."BARR_BARRIO_PK"  ENABLE;
ALTER TABLE "SYSPR1"."BARRIOS" ADD CONSTRAINT "BARR_DESCRIPCION_UK" UNIQUE ("BARR_DESCRIPCION")
  USING INDEX "SYSPR1"."BARR_DESCRIPCION_UK"  ENABLE;
ALTER TABLE "SYSPR1"."CIUDADES" ADD CONSTRAINT "CIUD_CIUDAD_PK" PRIMARY KEY ("CIUD_ID_CIUDAD")
  USING INDEX "SYSPR1"."CIUD_CIUDAD_PK"  ENABLE;
ALTER TABLE "SYSPR1"."PERSONAS_SOCIOS" ADD CONSTRAINT "PESO_PERSONA_SOCIO_PK" PRIMARY KEY ("PESO_COD_PERSONA", "PESO_NRO_SOCIO")
  USING INDEX "SYSPR1"."PESO_PERSONA_SOCIO_PK"  ENABLE;
ALTER TABLE "SYSPR1"."PERSONAS_SOCIOS" ADD CONSTRAINT "PESO_NRO_SOCIO_UK" UNIQUE ("PESO_NRO_SOCIO")
  USING INDEX "SYSPR1"."PESO_NRO_SOCIO_UK"  ENABLE;
ALTER TABLE "SYSPR1"."PERSONAS" ADD CONSTRAINT "PERS_PERSONA_PK" PRIMARY KEY ("PERS_COD_PERSONA")
  USING INDEX "SYSPR1"."PERS_PERSONA_PK"  ENABLE;
ALTER TABLE "SYSPR1"."FUNCIONARIOS" ADD CONSTRAINT "FUNC_FUNCIONARIO_PK" PRIMARY KEY ("FUNC_NRO_FUNCIONARIO")
  USING INDEX "SYSPR1"."FUNC_FUNCIONARIO_PK"  ENABLE;
ALTER TABLE "SYSPR1"."PAISES" ADD CONSTRAINT "PAIS_PK" PRIMARY KEY ("PAIS_ID_PAIS")
  USING INDEX "SYSPR1"."PAIS_PK"  ENABLE;
ALTER TABLE "SYSPR1"."PAISES" ADD CONSTRAINT "PAIS_DESCRIPCION_UK" UNIQUE ("PAIS_DESCRIPCION")
  USING INDEX "SYSPR1"."PAIS_DESCRIPCION_UK"  ENABLE;
ALTER TABLE "SYSPR1"."CALLES" ADD CONSTRAINT "CALL_CALLE_PK" PRIMARY KEY ("CALL_ID_CALLES")
  USING INDEX "SYSPR1"."CALL_CALLE_PK"  ENABLE;
-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/STATISTICS/INDEX_STATISTICS
-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/REF_CONSTRAINT
ALTER TABLE "SYSPR1"."PERSONAS_SOCIOS" ADD CONSTRAINT "PESO_PERSONA_FK" FOREIGN KEY ("PESO_COD_PERSONA")
	  REFERENCES "SYSPR1"."PERSONAS" ("PERS_COD_PERSONA") ENABLE;
ALTER TABLE "SYSPR1"."PERSONAS" ADD CONSTRAINT "PERS_PAIS_FK" FOREIGN KEY ("PERS_ID_PAIS")
	  REFERENCES "SYSPR1"."PAISES" ("PAIS_ID_PAIS") ENABLE;
ALTER TABLE "SYSPR1"."PERSONAS" ADD CONSTRAINT "PERS_CIUDAD_FK" FOREIGN KEY ("PERS_ID_CIUDAD")
	  REFERENCES "SYSPR1"."CIUDADES" ("CIUD_ID_CIUDAD") ENABLE;
ALTER TABLE "SYSPR1"."PERSONAS" ADD CONSTRAINT "PERS_FUNCIONARIO_FK" FOREIGN KEY ("PERS_NRO_FUNCIONARIO")
	  REFERENCES "SYSPR1"."FUNCIONARIOS" ("FUNC_NRO_FUNCIONARIO") ENABLE;
ALTER TABLE "SYSPR1"."FUNCIONARIOS" ADD CONSTRAINT "FUNC_PERSONA_FK" FOREIGN KEY ("FUNC_COD_PERSONA")
	  REFERENCES "SYSPR1"."PERSONAS" ("PERS_COD_PERSONA") ENABLE;
-- new object type path: SCHEMA_EXPORT/TABLE/TRIGGER
-- CONNECT SYSPR1
CREATE EDITIONABLE TRIGGER "SYSPR1".trg_persona
 BEFORE
  INSERT OR DELETE OR UPDATE
 ON personas
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Declare
    EXC_UPDATE  EXCEPTION;
    V_NRO_FUNC  NUMBER;

Begin

    V_NRO_FUNC := FC_RECU_NRO_FUNC(USER);
    IF DELETING THEN
        null;
    ELSIF INSERTING THEN
        :NEW.PERS_NRO_FUNCIONARIO := V_NRO_FUNC;
        :NEW.PERS_FECHA_USUARIO   := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.PERS_NRO_FUNCIONARIO := V_NRO_FUNC;
        :NEW.PERS_FECHA_USUARIO   := SYSDATE;
    END IF;

EXCEPTION
    WHEN EXC_UPDATE THEN
        RAISE_APPLICATION_ERROR(-20002,'NO SE PUEDE ACTUALIZAR LA PERSONA');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001,'TRIGGER PERSONA - '||SQLERRM);
End;

/

ALTER TRIGGER "SYSPR1"."TRG_PERSONA" DISABLE;

ALTER TRIGGER "SYSPR1"."TRG_PERSONA" 
  COMPILE 
    PLSQL_OPTIMIZE_LEVEL=  2
    PLSQL_CODE_TYPE=  INTERPRETED    PLSCOPE_SETTINGS=  'IDENTIFIERS:NONE'
;
CREATE EDITIONABLE TRIGGER "SYSPR1".trg_val_persona_socio
 BEFORE
   INSERT OR UPDATE OF peso_ingreso, peso_nro_socio, peso_cod_persona
 ON personas_socios
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE

    VAR1                VARCHAR2(02);
    MI_EXCEPTION01      EXCEPTION;

    CURSOR C1 IS
        SELECT  'S' RESP
        FROM    PERSONAS_SOCIOS
        WHERE   PESO_COD_PERSONA = :NEW.PESO_COD_PERSONA
        AND     PESO_ACTIVO = 1
        ;

BEGIN

    /*IF INSERTING OR UPDATING THEN

        FOR V1 IN C1 LOOP

            VAR1 := V1.RESP;

        END LOOP;

        IF VAR1 = 'S' THEN

            RAISE MI_EXCEPTION01;

        END IF;

    END IF;*/NULL;

EXCEPTION
    WHEN MI_EXCEPTION01 THEN
        RAISE_APPLICATION_ERROR(-20001,' ESTA PERSONA ES UN SOCIO ACTIVO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002,' - ERROR: TRG_VAL_PERSONA_SOCIO - '||SQLCODE);

END;

/

ALTER TRIGGER "SYSPR1"."TRG_VAL_PERSONA_SOCIO" ENABLE;

ALTER TRIGGER "SYSPR1"."TRG_VAL_PERSONA_SOCIO" 
  COMPILE 
    PLSQL_OPTIMIZE_LEVEL=  2
    PLSQL_CODE_TYPE=  INTERPRETED    PLSCOPE_SETTINGS=  'IDENTIFIERS:NONE'
;
-- new object type path: SCHEMA_EXPORT/TABLE/STATISTICS/TABLE_STATISTICS
-- new object type path: SCHEMA_EXPORT/STATISTICS/MARKER
-- fixup virtual columns... 
-- done fixup virtual columns 
