DROP USER syscoop
  CASCADE
/

CREATE USER syscoop
IDENTIFIED BY oracle
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
/
GRANT ALTER ANY INDEX TO syscoop
/
GRANT ALTER ANY TABLE TO syscoop
/
GRANT ALTER ANY TRIGGER TO syscoop
/
GRANT ALTER USER TO syscoop
/
GRANT CREATE ANY INDEX TO syscoop
/
GRANT CREATE ANY SYNONYM TO syscoop
/
GRANT CREATE DATABASE LINK TO syscoop
/
GRANT CREATE PUBLIC DATABASE LINK TO syscoop
/
GRANT CREATE SESSION TO syscoop
/
GRANT DROP ANY SYNONYM TO syscoop
/
GRANT DROP ANY TABLE TO syscoop
/
GRANT DROP PUBLIC DATABASE LINK TO syscoop
/
GRANT DROP PUBLIC SYNONYM TO syscoop
/
GRANT UNLIMITED TABLESPACE TO syscoop
/
GRANT CONNECT TO syscoop
/
GRANT DBA TO syscoop
/
GRANT RESOURCE TO syscoop
/
ALTER USER syscoop DEFAULT ROLE ALL
/

